### ISSUE TITLE
TensorFlow-GPU should be in the version of 1.13.1, instead of 1.12.0 as described in requirements.txt

### ISSUE THREAD

**Issue by machengcheng2016** [yangarbiter/adversarial-nonparametrics#1]
TensorFlow-GPU should be the version of 1.13.1, instead of 1.12.0 as described in *requirements.txt*.

I installed tf v1.12.0, and got an error as *AttributeError: module 'tensorflow.python.keras.backend' has no attribute 'get_graph'* when trying to run main.py.
After upgraded tf to 1.13.1, everything's OK.

**Comment by yangarbiter** [comment]
Thanks. I've updated it on dbc67e5
